image: 'docker-hosted.artifactory.tcsbank.ru/eva-io/eva-edu-image-ci:release-1'

variables:
  CHROMEDRIVER_SKIP_DOWNLOAD: "true"
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"

stages:
  - ğŸ§ª test

ğŸ¤ e2e-tests:
  stage: ğŸ§ª test
  script:
    - npm ci
    - npm test